apiVersion: v1
kind: Namespace
metadata:
  name: foo
  labels:
    environment-id: env_919bf4f6-b0f2-43e6-9b9a-8cf52cdbb60b
    project-id: project_919d8eac-0ba0-40d5-92ee-7fe445937e01
    project-name: dogHouse5
    environment-name: dev
    organization-id: org_01b50229-db34-43d4-8f3e-d1aeb683d900
